global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: platform-api-prod

    ecs_sd_configs:
      - region: us-west-2
        clusters: [platform-cluster]
        refresh_interval: 60s

    relabel_configs:
      - source_labels: ["__meta_ecs_service"]
        regex: "api-service-(blue|green)"
        action: keep

      - source_labels: ["__meta_ecs_ip_address"]
        target_label: "__address__"
        replacement: "${1}:8000"

      - target_label: "environment"
        replacement: "prod"

      - source_labels: ["__meta_ecs_cluster"]
        target_label: "cluster"

      - source_labels: ["__meta_ecs_service"]
        target_label: "service"

      - source_labels: ["__meta_ecs_service"]
        regex: "api-service-(blue|green)"
        target_label: "deployment"
        replacement: "${1}"

    metrics_path: /metrics
    scheme: http

