general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
  monitor =
  color = rgba(0, 0, 0, 1.0)
}

input-field {
  monitor =
  size = 300, 50
  outline_thickness = 2
  dots_size = 0.33
  dots_spacing = 0.15
  dots_center = true
}
